// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace OmgppNative
{
    public static unsafe partial class OmgppServerNative
    {
        const string __DllName = "client_server";



        [DllImport(__DllName, EntryPoint = "server_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* server_create(byte* ip, ushort port);

        [DllImport(__DllName, EntryPoint = "server_process", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_process(void* server);

        [DllImport(__DllName, EntryPoint = "server_register_on_connect_requested", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_register_on_connect_requested(void* server, delegate* unmanaged[Cdecl]<UuidFFI, EndpointFFI, bool> callback);

        [DllImport(__DllName, EntryPoint = "server_register_on_connection_state_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_register_on_connection_state_change(void* server, delegate* unmanaged[Cdecl]<UuidFFI, EndpointFFI, ConnectionState, void> callback);

        [DllImport(__DllName, EntryPoint = "server_register_on_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_register_on_message(void* server, delegate* unmanaged[Cdecl]<UuidFFI, EndpointFFI, long, byte*, nuint, void> callback);

        [DllImport(__DllName, EntryPoint = "server_register_on_rpc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_register_on_rpc(void* server, delegate* unmanaged[Cdecl]<UuidFFI, EndpointFFI, bool, long, ulong, long, byte*, nuint, void> callback);

        [DllImport(__DllName, EntryPoint = "server_send", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_send(void* server, UuidFFI* uuid, long msg_type, byte* data, nint offset, nuint size);

        [DllImport(__DllName, EntryPoint = "server_send_reliable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_send_reliable(void* server, UuidFFI* uuid, long msg_type, byte* data, nint offset, nuint size);

        [DllImport(__DllName, EntryPoint = "server_broadcast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_broadcast(void* server, long msg_type, byte* data, nint offset, nuint size);

        [DllImport(__DllName, EntryPoint = "server_broadcast_reliable", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_broadcast_reliable(void* server, long msg_type, byte* data, nint offset, nuint size);

        [DllImport(__DllName, EntryPoint = "server_call_rpc", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_call_rpc(void* server, UuidFFI* client, [MarshalAs(UnmanagedType.U1)] bool reliable, long method_id, ulong request_id, long arg_type, byte* arg_data, nint arg_data_offset, nuint arg_data_size);

        [DllImport(__DllName, EntryPoint = "server_call_rpc_broadcast", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_call_rpc_broadcast(void* server, [MarshalAs(UnmanagedType.U1)] bool reliable, long method_id, ulong request_id, long arg_type, byte* arg_data, nint arg_data_offset, nuint arg_data_size);

        [DllImport(__DllName, EntryPoint = "server_disconnect", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_disconnect(void* _server, UuidFFI* uuid);

        [DllImport(__DllName, EntryPoint = "server_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void server_destroy(void* server);


    }



}
