// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Sample.Messages {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIPc2FtcGxlLm1lc3NhZ2VzGg1tZXNzYWdlLnBy",
            "b3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8yxwEKDEdhbWVDb21t",
            "YW5kcxI4CghNb3ZlTGVmdBIVLnNhbXBsZS5tZXNzYWdlcy5Wb2lkGhUuc2Ft",
            "cGxlLm1lc3NhZ2VzLlZvaWQSQwoJTW92ZVJpZ2h0Ehguc2FtcGxlLm1lc3Nh",
            "Z2VzLk1lc3NhZ2UaHC5zYW1wbGUubWVzc2FnZXMuTWVzc2FnZVRlc3QSOAoG",
            "TW92ZVVwEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3Rv",
            "YnVmLkVtcHR5"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::awd.awd.MessageReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
